config/routes.rb
Gmaps::Application.routes.draw do
  require 'subdomain'

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
    get "sign_out", :to => "devise/sessions#destroy"
    match "/users/update" => "users#update_user"
  end

  resources :plans do
    collection do
      get :choose_plan
    end
  end
  
    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv        
        post :import_records
        get :reminder_email
      end
      resources :markers
    end
    resources :sms
    resources :companies    
    resources :assets
    resources :notification_settings
    resources :company_users
    resources :templates do
      collection do
        get :update_template
      end
    end

  namespace :admin do
    resources :users do
      collection do
        get :new_company
        post :create_company
        get :new_company_user
        post :create_company_user
      end
    end

    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv
        post :import_records
      end
    end
    resources :sms
    resources :companies
    resources :plans
    resources :assets
    resources :templates do
      collection do
        get :update_template
      end
    end
  end

  root :to => 'welcome#index'
  match "/set_position" => "characters#set_position"

  get "characters/:id/emailcontract" => "characters#send_contract", :as => "email_contract"
  get "characters/:id/smscontract" => "characters#send_sms", :as => "sms_contract"

end

app/views/templates/edit.html.erb
<%=form_for @template, :url => template_path do |f|%>
  Subject: <br/>
  <%= f.text_field :subject %><br/>


  <%#*Body: <br/>%>
  <%#= f.text_area :body, :class => "tinymce" %>
  <div style="float:left;width:100%;">
    <div style="float:left;">
      Body: <br/>
      <%= f.text_area :body, :value =>  @template.body.gsub('"',''),:class => "tinymce", :id => "template_body" %><br/>
    </div>

    <div style="float:left;margin-top: 20px; margin-left:20px;">
      <% fields = Character.columns.map {|c| c.name } %>
      <%= select_tag "field_vals", options_for_select([["name","name"],["address","address"]]),:prompt => "Select Fields",:onchange => "render_template(this.value)" , :class => "input"%>
    </div>
  </div>

  signature: <br/>
  <%= f.text_area :signature, :class => "tinymce" %><br/>
  <%= tinymce %>

  <%=f.submit "update"%>

<%end%>
<script type="text/javascript">
  function render_template(val){
    val = "<input type='button' value="+val+"></input>&nbsp;"
    tinyMCE.execInstanceCommand('template_body',"mceInsertContent",false,val);
  }
</script>

app/views/templates/index.html.erb
<br/><br/>
<%unless @templates.blank?%>
  <%@templates.each do |temp|%>
    Body: <br/>
    <%=raw(temp.body)%> <br/><%=link_to "Edit", edit_template_path(temp)%><%=link_to "Delete", template_path(temp), :method => :delete, :confirm => "Are you sure!"%><br/>
  
  <%end%>
<%else%>
  There are no templates to show!
<%end%>

  <%=link_to "create a template", new_template_path%>

app/views/templates/new.html.erb
<style type="text/css">
  p{
    margin: 0px;
    padding: 0px;
  }
</style>

<%= form_for @template, :url => templates_path do |f|%>
  Subject: <br/>
  <%= f.text_field :subject %><br/>

  <div style="float:left;width:100%;">
    <div style="float:left;">
      Body: <br/>
      <%= f.text_area :body, :class => "tinymce", :id => "template_body" %><br/>
    </div>

    <div style="float:left;margin-top: 20px; margin-left:20px;">
      <% fields = Character.columns.map {|c| c.name } %>
      <%= select_tag "field_vals", options_for_select([["name","name"],["address","address"]]),:prompt => "Select Fields",:onchange => "render_template(this.value)" , :class => "input"%>
    </div>
  </div>

  signature: <br/>
  <%= f.text_area :signature, :class => "tinymce" %><br/>
  <%= tinymce %>

  <%= f.submit "Create" %>

<%end%>

<script type="text/javascript">
  function render_template(val){
    val = "<input type='button' value="+val+"></input>&nbsp;"
    tinyMCE.execInstanceCommand('template_body',"mceInsertContent",false,val);
  }
</script>