config/routes.rb
Gmaps::Application.routes.draw do
  require 'subdomain'

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
    get "sign_out", :to => "devise/sessions#destroy"
    match "/users/update" => "users#update_user"
  end

  resources :plans do
    collection do
      get :choose_plan
    end
  end
  
    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv        
        post :import_records
        get :reminder_email
      end
      resources :markers
    end
    resources :sms
    resources :companies    
    resources :assets
    resources :notification_settings
    resources :company_users
    resources :templates do
      collection do
        get :update_template
      end
    end

  namespace :admin do
    resources :users do
      collection do
        get :new_company
        post :create_company
        get :new_company_user
        post :create_company_user
      end
    end

    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv
        post :import_records
      end
    end
    resources :sms
    resources :companies
    resources :plans
    resources :assets
    resources :templates do
      collection do
        get :update_template
      end
    end
  end

  root :to => 'welcome#index'
  match "/set_position" => "characters#set_position"

  get "characters/:id/emailcontract" => "characters#send_contract", :as => "email_contract"
  get "characters/:id/smscontract" => "characters#send_sms", :as => "sms_contract"

end

app/models/marker.rb
class Marker < ActiveRecord::Base
  attr_accessible :photo, :duration, :character_id

  belongs_to :character

  has_attached_file :photo,
  :storage => :filesystem, :path => ":rails_root/public/:class/:attachment/:id/:basename.:extension",
#  :storage => 's3',
#    :s3_credentials => {:access_key_id => "AKIAJYUYZM5LGPF5NAVA" ,:secret_access_key => "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",:s3_endpoint => 'popupstorz.s3-website-eu-west-1.amazonaws.com'},
#    :bucket => "popupstorz",
#    :path => "/system/ugc/:class/:id/:style/:basename.:extension",
    :default_style => :original

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_filter :load_character
  
  def index
    @markers = @character.markers
  end
  
  def new
    @marker = @character.markers.build
  end

  def create
    upload_markers
    return redirect_to characters_path
  end

  def edit
    #    @item = Item.find(params[:id])
    @avatar = @item.avatars
    unless @avatars.blank?
      @avatar = @avatars.first
    else
      @avatar = Avatar.new
      #      @avatar = @item.avatars.build
    end
  end
  
  def update
    upload_pics
    redirect_to items_path
  end
  
  def upload_markers
    (0..4).each do |a|      
      unless params[:marker][:markers]['photo_'+a.to_s].blank?
        params[:marker][:markers][:photo] = params[:marker][:markers]['photo_'+a.to_s]
        params[:marker][:markers].delete("#{'photo_'+a.to_s}")
        case a
        when 0          
          params[:marker][:markers][:duration] = "0"
        when 1
          params[:marker][:markers][:duration] = "1"
        when 2
          params[:marker][:markers][:duration] = "7"
        when 3
          params[:marker][:markers][:duration] = "15"
        else
          params[:marker][:markers][:duration] = "30"
        end        
        @marker = @character.markers.build(params[:marker][:markers])
        if @marker.save
          flash[:notice] = "Marker uploaded successfully!"
        else
          flash[:notice] = "Markrer can't be uploaded please try agian or later!"
        end
      end
    end
  end

  def destroy
    @marker = Marker.find_by_id(params[:id])
    if @marker.destroy
      flash[:notice] = "Marker is deleted successfully!"      
    else
      flash[:notice] = "Can't delete marker, Please try again or later!"
    end
    return redirect_to character_markers_path(params[:character_id])
  end

  protected
  def load_character
    @character = Character.find(params[:character_id])
    if @character.blank?
      flash[:notice] = "Character not found please try again or later!"
      redirect_to "/"
    end
  end
end

app/views/markers/_form.html.erb
<div style="padding: 20px;">
  <div id="lisit-name"><h1><%= @character.name %></h1></div>

  <div id="show-thumbnail">
    <% unless @marker.new_record? %>
      <div id="thumbnail">
        <%= image_tag(@marker.marker.url )%>
      </div>
    <%end%>
  </div>
  <div>    
    <br/>
    <br/>
    <% if @marker.new_record? %>
      <%= f.fields_for :markers do |marker| %>
        <%= "General Marker" %>
        <%= marker.file_field :photo_0 %><br />
        <%#= file_field_tag "photo_0" %>
        <%= "Daily Expiry Marker" %>
        <%= marker.file_field :photo_1 %><br />
        <%= "Weekly Expiry Marker" %>
        <%= marker.file_field :photo_2 %><br />
        <%= "Bi-Month Expiry Marker" %>
        <%= marker.file_field :photo_3 %><br />
        <%= "Monthly Expiry Marker" %>
        <%= marker.file_field :photo_4 %><br />
        <%= hidden_field_tag "character_id","#{@character_id}" %><br />
      <% end %>
    <%else%>
      <br/>
      <br/>
      <%@marker.each do |marker|%>
        <%= image_tag(marker.photo.url(:large) )%>
        <br/>
        <br/>
        <%= link_to t(:delete_photo), character_marker_path(@character,marker), :method => :delete, :confirm => "Are you sure to delete" %>
      <%end%>
    <%end%>
    <br/>
    <br/>

<%# if @avatar.new_record? %>
    <center>
      <button type="submit" class = "search" >
        <%= "Update Markers" %>
      </button>
    </center>
<%#end%>
  </div>

</div>

app/views/markers/edit.html.erb
<%= form_for([@item, @avatar], :html => { :multipart => true, :class => "new_marker_form"}) do |f|%>
  <div id="thumnail-details">
    <span class="familar-photo"> <%= t(:photo) %> </span>
   
  <% end %>

</div>

app/views/markers/index.html.erb
<div class="container">
  <label style="color:#FFFFFF">Markers</label>
  <% @markers.each do |m| %>    
    <%= image_tag(m.photo.url(:original) )%>
    <br/>
    <br/>
    <%= link_to  "Delete" , character_marker_path(@character,m), :method => :delete, :confirm => "Are you sure to delete" %>
    <br/>
    <br/>
  <% end %>
  <br /><br />
  <%= link_to "New Markers", new_character_marker_path(@character.id) %>
</div>

app/views/markers/new.html.erb
<%= form_for([@character, @marker], :html => { :multipart => true, :class => "new_marker_form"}) do |f|%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>