config/routes.rb
Gmaps::Application.routes.draw do
  require 'subdomain'

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
    get "sign_out", :to => "devise/sessions#destroy"
    match "/users/update" => "users#update_user"
  end

  resources :plans do
    collection do
      get :choose_plan
    end
  end
  
    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv        
        post :import_records
        get :reminder_email
      end
      resources :markers
    end
    resources :sms
    resources :companies    
    resources :assets
    resources :notification_settings
    resources :company_users
    resources :templates do
      collection do
        get :update_template
      end
    end

  namespace :admin do
    resources :users do
      collection do
        get :new_company
        post :create_company
        get :new_company_user
        post :create_company_user
      end
    end

    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv
        post :import_records
      end
    end
    resources :sms
    resources :companies
    resources :plans
    resources :assets
    resources :templates do
      collection do
        get :update_template
      end
    end
  end

  root :to => 'welcome#index'
  match "/set_position" => "characters#set_position"

  get "characters/:id/emailcontract" => "characters#send_contract", :as => "email_contract"
  get "characters/:id/smscontract" => "characters#send_sms", :as => "sms_contract"

end

app/models/character.rb
#require 'geocoder/models/active_record'
class Character < ActiveRecord::Base

  extend ::Geocoder::Model::ActiveRecord

  geocoded_by :address_for_geocode
  reverse_geocoded_by :latitude, :longitude

  belongs_to :user
  attr_accessible :address, :fences, :gmaps, :latitude, :longitude, :name, :contractendon, :email, :contract_number, :mobile_number, :user_id
  validates :email, :presence => true
  validates :address, :presence => true
  validates :contractendon, :presence => true
  validates :mobile_number, :presence => true
  validates :contract_number, :presence => true, :uniqueness => true

  acts_as_gmappable
  
  has_many :markers
  accepts_nested_attributes_for :markers, :allow_destroy => true
  #  searchable do
  #    text :address, :name, :email, :stored => true
  #    integer :fences, :stored => true
  #    integer :contract_number, :stored => true
  #    integer :mobile_number, :stored => true
  #    time    :contractendon, :stored => true
  #    integer :user_id, :stored => true
  #  end
  def lessthan?
    if self.contractendon < 14.day.since.to_date && self.contractendon > Time.now.to_date
      return true
    end
  end

  def two_week_reminder?
    if self.contractendon < 14.day.since.to_date && self.contractendon > Time.now.to_date
      return true
    end
  end

  def weekly_reminder?
    if self.contractendon < 7.day.since.to_date && self.contractendon > Time.now.to_date
      return true
    end
  end

  def monthly_reminder?
    if self.contractendon < 30.day.since.to_date && self.contractendon > Time.now.to_date
      return true
    end
  end

  def expiretoday?
    if self.contractendon <= Time.now.to_date
      return true
    end
  end

  def self.send_reminder_email
    Character.all.each do |cont|
      setting = cont.user.notification_setting
      unless setting.blank?
        if setting.oneday_reminder
          if cont.expiretoday?            
            CharacterExpiry.contract_email(cont,cont.user,cont.user.company.message_templates.last).deliver
          end
        end
        if setting.weekly_reminder
          if cont.weekly_reminder?
            
            CharacterExpiry.contract_email(cont,cont.user,cont.user.company.message_templates.last).deliver
          end
        end
        if setting.monthly_reminder
          if cont.monthly_reminder?            
            CharacterExpiry.contract_email(cont,cont.user,cont.user.company.message_templates.last).deliver
          end
        end
        if setting.bimonthly_reminder
          if cont.two_week_reminder?            
            CharacterExpiry.contract_email(cont,cont.user,cont.user.company.message_templates.last).deliver
          end
        end
      end
    end
  end

  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
    "<b>#{name}</b>
  <p>
  <b><i> Number of Fences: #{fences}</b></i> </p>"
  end
  
  def gmaps4rails_marker_picture
    unless self.markers.blank?
      marker = ""
      if monthly_reminder?
        marker = self.markers.where("duration = '30'")
        set_marker(marker)
      elsif two_week_reminder?
        marker = self.markers.where("duration = '15'")
        set_marker(marker)
      elsif weekly_reminder?
        marker = self.markers.where("duration = '7'")
        set_marker(marker)
      elsif expiretoday?
        marker = self.markers.where("duration = '0'")
        set_marker(marker)
      else
        set_marker(marker)
      end
    else
      set_marker(marker)
    end
  end

  def set_marker(marker)    
    if marker.blank?
      {
        "picture" => "/images/fencered.png",
        "width" => "25",
        "height" => "39"
      }
    else
      marker = marker.first
      {
        "picture" => "/markers/photos/#{marker.id}/#{marker.photo_file_name}",
        "width" => "25",
        "height" => "39"
      }
    end
    
  end
  
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  require 'will_paginate/array'
  require 'csv'
  # GET /characters
  # GET /characters.json
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def send_contract
    @character = current_user.characters.find(params[:id])
    CharacterExpiry.contract_email(@character,current_user,current_user.company.message_templates.last).deliver

    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Email was successfully sent'  }
      format.json { head :no_content }
    end
  end

  def send_sms
    @character = current_user.characters.find(params[:id])
    api = Clickatell::API.authenticate('3415596', 'sbsfence','sbsfence123')
    api.send_message(@character.mobile_number, "Your Rental Contract is expiring soon")
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'SMS was successfully sent'  }
      format.json { head :no_content }
    end
  rescue Clickatell::API::Error => e
    respond_to do |format|
      format.html { redirect_to characters_url, error: "Clickatell API error: #{e.message}" }
      format.json { head :no_content }
    end
  end

  def index
    if user_signed_in?
      if (params[:search])
        if(params[:search] == "all" || params[:search] == "")
          @characters = current_user.characters.find(:all, :order => :contractendon)
        else
          @search = current_user.characters.search do
            fulltext params[:search]
          end
          @characters = @search.results
          
          @characters = @characters.paginate(:page => params[:page], :per_page => 2)
        end
      else
        @characters = current_user.characters.find(:all, :order => :contractendon)
        
        @characters = @characters.paginate(:page => params[:page], :per_page => 2)
      end
      #      @json = @characters.to_gmaps4rails
      @json = current_user.characters.all.to_gmaps4rails
      
      respond_to do |format|
        format.html
        format.json { render json: @characters }
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = current_user.characters.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = current_user.characters.new
    @assets = Asset.where(:company_id => current_user.company_id)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @assets = Asset.where(:company_id => current_user.company_id)
    @character = current_user.characters.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
   
    @character = current_user.characters.new(params[:character])
    @assets = Asset.where(:company_id => current_user.company_id)
    respond_to do |format|
      format.html do
        if @character.save!
          unless params[:assets].blank?
            params[:assets].each do|a|
              asset = Asset.find_by_name(a)
              @character.assets << asset
            end
          end
          redirect_to characters_path, notice: 'Character was successfully created.'
        else
          render action: "new"
        end
      end
      format.js do
        if @character.save
          format.json { render json: @character, status: :created, location: @character }
        else
          format.json { render json: @character.errors, status: :unprocessable_entity }
        end

      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = current_user.characters.find(params[:id])
    @assets = Asset.where(:company_id => current_user.company_id)
    #    respond_to do |format|
    if @character.update_attributes(params[:character])
      #        solr.update(:character)
      redirect_to @character, notice: 'Character was successfully updated.'
      #        format.json { head :no_content }
    else
      render action: "edit"
      #        format.json { render json: @character.errors, status: :unprocessable_entity }
    end
    #    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = current_user.characters.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  def view_full_map
    @json = current_user.characters.all.to_gmaps4rails
  end

  def set_position
    @character = Character.find(params[:id])
    @json = @character.to_gmaps4rails
  end

  def export_to_csv
    @characters = current_user.characters
    csv_string = CSV.generate do |csv|
      csv << ["contract number", "name", "address", "contract ends on", "location", "gmaps","email","mobile number"]
      @characters.each_with_index do |chr|
        addr = ""
        if !chr.latitude.blank? and !chr.longitude.blank?
          addr = chr.latitude.to_s+","+chr.longitude.to_s
        end
        unless addr.blank?
          location = Geocoder.search(addr) if !addr.blank?
          unless location.blank?
            addr = location[0].address
          end
        end
        csv << [chr.contract_number,chr.name, chr.address, chr.contractendon, addr, chr.gmaps,chr.email,chr.mobile_number]
      end
    end
    send_data csv_string, :filename => "output.csv" , :type=>"text/csv"
  end

  def import_records
    data_file = params[:data_file].read
    CSV.parse(data_file).each_with_index do |row,i|
      if i > 0
        @check_character = Character.find_by_contract_number(row[0])
        #        Get the latitude and longitude from the location
        lat = ""
        long = ""
        unless row[4].blank?
          a = Geocoder.search(row[4])
          unless a.blank?
            lat = a[0].latitude
            long = a[0].longitude
          end
        end

        if @check_character.blank?
          @new_character = Character.new(:contract_number => row[0],:name => row[1],
            :address => row[2], :contractendon => row[3],
            :latitude => lat,:longitude => long, :gmaps => row[5], :email => row[6],
            :mobile_number => row[7], :user_id => current_user.id)
          @new_character.save
        else
          @check_character.name = row[1]
          @check_character.address = row[2]
          @check_character.contractendon = row[3]
          @check_character.latitude = lat
          @check_character.longitude = long
          @check_character.gmaps = row[5]
          @check_character.email = row[6]
          @check_character.mobile_number = row[7]
          @check_character.user_id = current_user.id
          @check_character.save
        end
      end
    end
    redirect_to characters_path
  end

  def reminder_email
    Character.send_reminder_email
    redirect_to :back
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<div class = "formcontract">
  <%= simple_form_for @character, :html => { :class => 'form-horizontal well' } do |f| %>
    <fieldset>
      <div class ="control-group">
        <%= f.input :contract_number %>
      </div>
      <div class ="control-group">
        <%= f.input :name %>
      </div>
      <div class ="control-group">
        <%= f.input :address %>
      </div>
      <div class ="control-group">
        <%= f.input :email %>
      </div>
      <div class ="control-group">
        <%= f.input :mobile_number %>
      </div>

      <div class ="control-group">
        Contract Ends On <br />
        <%= f.text_field :contractendon, :id => 'dateselect' %>
      </div>
      <div class ="control-group">
        <%= f.input :longitude %>
      </div>
      <div class ="control-group">
        <%= f.input :latitude %>
      </div>
      
      <div class ="control-group">
        <%= select_tag( "assets", options_from_collection_for_select( @assets, :name, :name), :prompt => "Select Assets",  :multiple => true ) %>
      </div>
      <div class ="control-group">
        <%= f.input :gmaps %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, :class => 'btn-primary' %>

        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          characters_path, :class => 'btn' %>
      </div>
    <% end %>
  </fieldset>
</div>

app/views/characters/_map_partial.html.erb
<%= gmaps("map_options" => {"center_latitude" => lat.blank? ? "" : lat,
    "center_longitude" => long.blank? ? "" : long,
    "detect_location" => false,
    "center_on_user" => false,
    "auto_adjust" => false,
    "auto_zoom" => true,
    "zoom" => 8 },
  :markers => { :data => @json  }
)%>

app/views/characters/edit.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1>Edit Contract</h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/index.html.erb
<header class ="jumbotron subhead" id="overview"><div class = "row">

    <%= current_user.id %>

    <fieldset><%- model_class = Character -%>
      <section id="tables">
        <div class="page-header" align="center">
          <h1>SBS Fence Pty Ltd</h1>
          <p>
            <%= flash[:notice] %>
          </p>
          <!--
          <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
          -->
        </div>
        </header>
        <h2> Search Contracts </h2>
        <%= form_tag characters_path, :method => :get do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
        <% end %>
        <div class ="page-header">
          <h1>Rental Contracts</h1>
        </div>

        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th> </th>
             <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
              <th><%= model_class.human_attribute_name(:name) %></th>
              <th><%= model_class.human_attribute_name(:address) %></th>
              <th>Contract Ends On</th>
              <th><%= model_class.human_attribute_name(:fences) %></th>


              <!--
              <th><%= model_class.human_attribute_name(:longitude) %></th>
              <th><%= model_class.human_attribute_name(:latitude) %></th>
              <th><%= model_class.human_attribute_name(:fences) %></th>
              <th><%= model_class.human_attribute_name(:gmaps) %></th>
              <th><%= model_class.human_attribute_name(:created_at) %></th>
              -->
              <th><%=t '.actions', :default => t("helpers.actions") %></th>
            </tr>
          </thead>
          <tbody>
            <% @characters.each do |character| %>
              <% if character.lessthan? %>
                <tr class = "warning">
                  <td> Expiring within 14 days
                  </td>
                <% elsif character.expiretoday? %>
                <tr class = "error">
                  <td>Expired</td>
                <% else %>
                <tr>
                  <td></td>
                <% end %>

                  <!--<td><%= link_to character.id, character_path(character) %></td>-->
                <td><span id="map_<%=character.id%>" onclick="set_map_position(<%=character.id%>)" style="cursor: pointer"> <%= character.name %></span></td>
                <td><%= character.address %></td>
                <td><%= character.contractendon %></td>
                <td><%= character.fences %></td>

                   <!--  <td><%= character.longitude %></td>
                     <td><%= character.latitude %></td>
                     <td><%= character.fences %></td>
                     <td><%= character.gmaps %></td>
                     <td><%=l character.created_at %></td>
                -->
                <td>
                  <div>
                    <div>
                      <button class="rerun">Actions</button>
                      <button class="select">Select an action</button>
                    </div>
                    <ul>
                      <li>Actions</li>
                      <li><%= link_to 'Markers', character_markers_path(character.id) %></li>
                      <li><%= link_to 'Edit', edit_character_path(character) %></li>
                      <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          character_path(character),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %></li>
                      <li><%= link_to 'Send Email', email_contract_path(character) %></li>
                      <li><%= link_to 'Send Sms', sms_contract_path(character) %></li>
                    </ul>
                  </div>

                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </fieldset>
    <%=link_to "Export to csv", export_to_csv_characters_path%><br/><br/>
    <%=form_tag import_records_characters_path, :multipart => true do |f|%>
      upload data:<%=file_field_tag "data_file"%>
      <%=submit_tag "import"%>
    <%end%>
    <%= will_paginate @characters %>

    <%= link_to t('.new', :default => t("helpers.links.new")),
      new_character_path,
      :class => 'btn btn-primary btn-large' %>
    </section>
    <section id = "typography">
      <div class="page-header">
        <h2>MAP</h2>
      </div>
    </section>
    
    <div id="map_div">
      <%#= gmaps("map_options" => {"center_latitude" => 37,
          "center_longitude" => 37,
          "detect_location" => false,
          "center_on_user" => false,
          "auto_adjust" => false,
          "auto_zoom" => true,
          "zoom" => 8 },
        :markers => { :data => @json  }
      )%>
      <%#= gmaps("map_options" => {"center_latitude" => lat.blank? ? 37 : lat,
          "center_longitude" => long.blank? ? 37 : long,
          "detect_location" => false,
          "center_on_user" => false,
          "auto_adjust" => false,
          "auto_zoom" => true,
          "zoom" => 8 },
        :markers => { :data => @json  }
      )%>
    <%= render :partial => "map_partial", :locals => {:json => @json, :lat => "37", :long => "37"} %>
    </div>
    <%=link_to "View full screen", view_full_map_characters_path, :target => "_blank"%>


  </div>
  <script type="text/javascript">
    function set_map_position(cid){
    $.ajax({
    url: "/set_position?id="+cid
    })
    }
  </script>

app/views/characters/new.html.erb
<%- model_class = Character -%>
<!--<section id ="typography">
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %>
</div> -->
<div class = "formheading">
<h1> New Contract </h1>
</div>
<%= render :partial => 'form' %>
<%#*</section>%>

app/views/characters/set_position.js.erb
$('#map_div').html('<%= escape_javascript( gmaps({:last_map => false}) ) %>');
Gmaps.map = new Gmaps4RailsGoogle();
Gmaps.load_map = function() {
  Gmaps.map.map_options.maxZoom = 15;
  Gmaps.map.initialize();
  Gmaps.map.markers = <%= raw @json %>;
  Gmaps.map.create_markers();
  Gmaps.map.adjustMapToBounds();
  Gmaps.map.callback();
};
Gmaps.loadMaps();

app/views/characters/show.html.erb
<%- model_class = Character -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @character.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @character.address %></dd>
   <dt><strong>Email:</strong></dt>

  <dd><%= @character.email %></dd>
  <!--<dt><strong><%= model_class.human_attribute_name(:contractendon) %>:</strong></dt>-->
  <dt><strong>Contract Ends On:</strong></dt>

  <dd><%= @character.contractendon %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @character.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @character.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fences) %>:</strong></dt>
  <dd><%= @character.fences %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gmaps) %>:</strong></dt>
  <dd><%= @character.gmaps %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              characters_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_character_path(@character), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              character_path(@character),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/characters/view_full_map.html.erb
<%= gmaps4rails(@json) %>