config/routes.rb
Gmaps::Application.routes.draw do
  require 'subdomain'

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_for :users do
    get "sign_out", :to => "devise/sessions#destroy"
    match "/users/update" => "users#update_user"
  end

  resources :plans do
    collection do
      get :choose_plan
    end
  end
  
    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv        
        post :import_records
        get :reminder_email
      end
      resources :markers
    end
    resources :sms
    resources :companies    
    resources :assets
    resources :notification_settings
    resources :company_users
    resources :templates do
      collection do
        get :update_template
      end
    end

  namespace :admin do
    resources :users do
      collection do
        get :new_company
        post :create_company
        get :new_company_user
        post :create_company_user
      end
    end

    resources :characters do
      collection do
        get :view_full_map
        get :export_to_csv
        post :import_records
      end
    end
    resources :sms
    resources :companies
    resources :plans
    resources :assets
    resources :templates do
      collection do
        get :update_template
      end
    end
  end

  root :to => 'welcome#index'
  match "/set_position" => "characters#set_position"

  get "characters/:id/emailcontract" => "characters#send_contract", :as => "email_contract"
  get "characters/:id/smscontract" => "characters#send_sms", :as => "sms_contract"

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :title, :description, :frequency, :price, :plan_type
  belongs_to :company
  belongs_to :user
  has_and_belongs_to_many :fee_plans, :class_name => 'User', :join_table => 'plan_users', :association_foreign_key => 'user_id'
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  layout "admin"
  def index
    @plans = Plan.all
#    if @plans.blank?
#      redirect_to "/"
#    end
  end
  
  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params[:plan])
    @plan.save
    redirect_to plans_path
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update_attributes(params[:plan])
    @plan.save
    redirect_to plans_path
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  def choose_plan    
    @user = User.find(params[:user])
    if @user.blank?
      redirect_to "/"
    end
    render :layout => "application"
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/choose_plan.html.erb
<div class="clearfix"></div>
<div class="clearfix"></div>
<div class="whitecontainer">
  <div class="container">
    <div class="row-fluid">
      <div class="partition span10 offset1">
        <div class="heading">
							Pricing
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row-fluid">
      <div class="span12 opning_line">
        Feature updates, automatic backups, support and more – for free. Get started now and <a href="#">signup for your free trial</a>.
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row-fluid">
      <div class="span4 mutual_features">
        <h2>ALL PRICING PLANS INCLUDE</h2>
        <ul>
          <li>
                            	Free trial, pay nothing until you're ready
          </li>
          <li>
								No setup fees, upgrade fees or contracts
          </li>
          <li>
								Unlimited users
          </li>
          <li>
								Unlimited customer support
          </li>
          <li>
								Access anywhere online
          </li>
          <li>
								Automatic backups
          </li>
          <li>
								Pay by credit card
          </li>
          <li>
								Cancel online at any time
          </li>
        </ul>
      </div>
      <div class="span8 packages">
        <div class="package">
                        	$<span class="packageprice">19</span>USD PER MONTH

          <span class="packagename">small</span>
          <p>Ideal for freelancers and small property investors</p>
          <ul>
            <li>
                                	Send 5 invoices + receive 5 bills per month
            </li>
            <li>
									Reconcile 20 bank statement lines per month
            </li>
          </ul>
          <button class="btn btn-warning button_orange">SELECT</button>
        </div>
        <div class="package">
                        	$<span class="packageprice">19</span>USD PER MONTH

          <span class="packagename">small</span>
          <p>Ideal for freelancers and small property investors</p>
          <ul>
            <li>
                 Send 5 invoices + receive 5 bills per month
            </li>
            <li>
									Reconcile 20 bank statement lines per month
            </li>
          </ul>
          <button class="btn btn-warning button_orange">SELECT</button>
        </div>
        <div class="package">
        $<span class="packageprice">19</span>USD PER MONTH
          <span class="packagename">small</span>
          <p>Ideal for freelancers and small property investors</p>
          <ul>
            <li>
              Send 5 invoices + receive 5 bills per month
            </li>
            <li>
              Reconcile 20 bank statement lines per month
            </li>
          </ul>
          <button class="btn btn-warning button_orange">SELECT</button>
        </div>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="row-fluid">
      <hr />
    </div>
  </div>

  <div class="clearfix"></div>
  <div class="row-fluid">
    <div class="well span8 offset2">
      <img src="/assets/tkff.png" /> &nbsp;&nbsp;&nbsp;&nbsp;Free trial, pay nothing until you're ready
    </div>
  </div>

</div>

app/views/plans/edit.html.erb
<div class="main-div">
  <%= form_for @plan, :url => plan_path do |f|%>
    <div class="left-div">
      Title: <br/>
      <%= f.text_field :title %><br/>

      <div class="left-container">
        <div style="float:left;">
          Description: <br/>
          <%= f.text_area :description, :class => "tinymce" %><br/>
          <%= tinymce %>
        </div>
      </div>
    </div>
    <div class="right-div">
      Price: <br/>
      <%= f.text_field :price %><br/>

      Frequency: <br/>
      <%= f.text_field :frequency %><br/>

      Type: <br/>
      <%= select_tag "plan[plan_type]", options_for_select([["SMS","sms"],["Package","package"]],@plan.plan_type),:prompt => "Select Fields", :class => "input", :style => "width:220px;" %>
      <br />
      <%= f.submit "Update", :style => "width:100px;" %>
    </div>

  <%end%>
</div>

app/views/plans/index.html.erb
<br/><br/>
<%unless @plans.blank?%>
  <%@plans.each do |plan|%>
    Title: <br/>
    <%=plan.title%> <br/>
    Description: <br/>
    <%= raw plan.description %> <br/>
    Frequency: <br/>
    <%=plan.frequency%> <br/>
    price: <br/>
    <%=plan.price%> <br/>
    <%= link_to "Edit", edit_plan_path(plan) %>&nbsp;&nbsp;|
    <%= link_to  "Delete" , plan_path(plan), :method => :delete, :confirm => "Are you sure to delete" %>
  <%end%>
<%else%>
  There are no plans to show
<%end%>

<br />
<%= link_to "Create a Plan", new_plan_path, :class => "input" %>

app/views/plans/new.html.erb
<div class="main-div">
  <%= form_for @plan, :url => plans_path do |f|%>

    <div class="left-div">
      Title: <br/>
      <%= f.text_field :title %><br/>

      <div class="left-container">
        <div style="float:left;">
          Description: <br/>
          <%= f.text_area :description, :class => "tinymce" %><br/>
          <%= tinymce %>
        </div>
      </div>
    </div>
    <div class="right-div">
      Price: <br/>
      <%= f.text_field :price %><br/>

      Frequency: <br/>
      <%= f.text_field :frequency %><br/>

      Type: <br/>
      <%= select_tag "plan[plan_type]", options_for_select([["SMS","sms"],["Package","package"]]),:prompt => "Select Fields", :class => "input", :style => "width:220px;" %>
      <br />
      <%= f.submit "Create", :style => "width:100px;" %>
    </div>
  <%end%>
</div>